### ISSUE TITLE
deploy: pip install issue (production)

### ISSUE THREAD

**Issue by seanderickson** [hmslincs/hmslincs#399]
There was an error checking the latest version of pip
Traceback (most recent call last):
  File "/www/lincs.hms.harvard.edu/support/virtualenv/lib/python2.7/site-packages/pip/utils/outdated.py", line 138, in pip_version_check
    state.save(pypi_version, current_time)
  File "/www/lincs.hms.harvard.edu/support/virtualenv/lib/python2.7/site-packages/pip/utils/outdated.py", line 38, in save
    with open(self.statefile_path, "w") as statefile:
IOError: [Errno 13] Permission denied: '/www/lincs.hms.harvard.edu/support/virtualenv/pip-selfcheck.json'

also:

python: can't open file 'src/do_pathway.py': [Errno 2] No such file or directory

@jmuhlich

**Comment by jmuhlich** [comment]
Did this ever get resolved? pip-selfcheck.json looks group-writeable to me now, and I fixed the latter error when i removed the `makeimg` call from deploy.

**Comment by seanderickson** [comment]
I have not seen this error with the last several deploys, so I think it is resolved.
